### ISSUE TITLE
paplay not in all distros

### ISSUE THREAD

**Issue by vasa1** [asheeshr/Bash-Scripts#1]
Following on from [your comment](http://askubuntu.com/questions/347937/generate-alert-on-high-cpu-usage/348679?noredirect=1#comment455801_348679), the distro I'm using is Lubuntu and it does not have Pulseaudio as default. One would have to install it additionally. See https://help.ubuntu.com/community/Lubuntu/Setup#Sound for that.

So, rather than just mentioning `paplay`, you could have a comment in the **customization** section at the top informing people that your script needs pulseaudio though **I agree that most other distros would have pulseaudio**.

Again, re. the location of the sound files, a comment would be useful to let people be aware that they need to (or could) set things up for their specific systems.

A similar situation is in line #98 where you refer to `/usr/share/icons/default.kde4/128x128/`. Would that be on Ubuntu distros other than Kubuntu (unless someone has installed the KDE environment)?

Anyway, I'm not knowledgeable on sound in Ubuntu but running `aplay /usr/share/sounds/alsa/*.wav` works for me in a terminal and so should work in your script.

**Comment by asheeshr** [comment]
I have some ideas as to how to make this really portable across multiple distros (given a bit of user editing of a config file). This might take some time, though. Stay tuned :)

**Comment by asheeshr** [comment]
I added support for a simple user-editable config file. The file is generated the first time the script is run. After that, the existing file is imported and used. 

The audio player, audio file, icon, and all other settings can be set in that file. Adding OS specific support beyond this did not seem <i>feasible</i> at this point. 

<b>Thanks for bringing this up!</b>
